### ISSUE TITLE
Allow VCEP curators to "Refresh" ClinVar Curator VCEP queue files

### ISSUE THREAD

**Issue by larrybabb** [clingen-data-model/curator#53] opened 2022-01-31 15:15 UTC
There is a permission error occurring when VCEP curators attempted to Refresh the ClinVar Curator VCEP queue google sheets.  We should enable most (if not all) curators to refresh the sheets so they can see the changes resulting from their annotations being submitted through the clinvar chrome extension.

DoD: Kelsea, Danielle, Heidi and other broad institute based google users using the ClinVar curation tool should be able to refresh the data in any of the VCEP queue files by doing the following:

(NOTE: Add an SCV annotation via the chrome extension for one or more of the SCVs in the current VCEP queue file so that you can identify it refreshed with the change at the end.)

1.  Open a VCEP queue google sheet.
2. Select the menu item Data > Data Connectors > Refresh Options
3. From the bottom of the Refresh Options window that appears on the right side of the sheet, click the "Refresh All" button.

After all the various tabs have finished refreshing (spinners will come to a stop) the data should reflect the recent changes made via the chrome extension.

**Comment by larrybabb** [comment] 2022-01-31 15:16
@KelseaChang5 last one for now... Can you verify that this "refresh" works for you in the VCEP files? I think you only need to test one file.

**Comment by KelseaChang5** [comment] 2022-01-31 15:23
@larrybabb I'm still getting a failed notification when I tried this (I attempted to refresh 2 different VCEP files)![Screen Shot 2022-01-31 at 9.21.58 AM.png](https://images.zenhubusercontent.com/6189303ebad10a9727d59b63/94e3fc13-2261-47ad-b998-bc6bbf347e72)

**Comment by KelseaChang5** [comment] 2022-02-02 14:39
Confirmed I am able to refresh now - closing ticket

**Closed as completed by KelseaChang5** 2022-02-02 14:39 UTC
Labels: bug, clinvar

**Comment by KelseaChang5** [comment] 2022-02-02 14:41
**Adding for context:**
Only users with a google account that is associated with an Enterprise Google workspace will be able to perform this refresh. Since all broadinstitute.org accounts have this they will all be able to do it. However, if you work with others outside of broad that do not have access to an enterprise google workspace they will likely not even be able to see the Data Connectors > Refresh Options menu let alone be able to run it
